CREATE TABLE studio_generations (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    token           VARCHAR(64) NOT NULL UNIQUE,
    user_id         BIGINT NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'pending',
    error           TEXT NULL,
    prompt          MEDIUMTEXT NOT NULL,
    revised_prompt  MEDIUMTEXT NULL,
    model           VARCHAR(64) NULL,
    size            VARCHAR(32) NULL,
    quality         VARCHAR(16) NULL,
    style           VARCHAR(16) NULL,
    n               INT NOT NULL DEFAULT 1,
    image_path      VARCHAR(256) NULL,
    source_path     VARCHAR(256) NULL,
    used_shared     TINYINT NOT NULL DEFAULT 0,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    finished_at     DATETIME(3) NULL,
    CONSTRAINT fk_studio_gen_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_studio_gen_user (user_id, created_at DESC),
    INDEX idx_studio_gen_status (status, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
